### ISSUE TITLE
Wrong second param.

### ISSUE THREAD

**Issue by asyven** [xTCry/fkwallet-api#1]
https://github.com/xTCry/node-fkwallet-api/blob/89481fd77239e8f282c207a5e8556b0b08cf67ca/src/api-client.ts#L67

sign | Контрольная подпись MD5, формируется из параметров wallet_id, amount, purse, и API ключа
md5('F123456789'.'10.23'.'F123456710'.'JG68NC68DJC8S0DCH6')

```md5(`${this.walletId}${payload.amount}${payload.purse}${this.apiKey}`)```

**Comment by xTCry** [comment]
fixed c2275c3149b9268699b7e9eb7c8f45ba59fcef77
